### ISSUE TITLE
Outdated Configuration Manager Requirement

### ISSUE THREAD

**Issue by JoeSenOne** [afilbert/valheim-silence-tame-wolfcub-howls-mod#6]
The Configuration Manager that is a requirement is quite outdated... there is a new version by Azumatt, the "Azus_UnOfficial_Configuration_Manager".
It would be nice if the requirement for the manager is just gone.

**Comment by afilbert** [comment]
That’s a good suggestion. I’ll see about getting a new version published.

**Comment by afilbert** [comment]
Went ahead and published a new version without the config manager requirement. [Here it is](https://valheim.thunderstore.io/package/GetOffMyLawn/SilenceTameWolfCub/). If that helps, please consider an upvote. :)

I'll update github with a release when I make some time.

**Comment by JoeSenOne** [comment]
Great job, thank you :). I'll gib it an upvote

**Comment by afilbert** [comment]
Resolved by #7
